---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: gogs-install-application
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
      - destroy
      - dependency
      - syntax
      - create
      - prepare
      - converge
#    - idempotence
#    - lint
      - side_effect
      - verify
      - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
